### PR TITLE
Include diagrams in recitation 11 notes

### PR DESCRIPTION
**Pull request by cjubb39**
Are the GIFs too distracting from the notes?

### CODE REVIEW

**Comment by kaitlinhuben** [comment]
I think they're helpful, with 2 caveats:
* They switch a little too fast
* They may be distracting in the body of the notes themselves, but I could go either way here

**Comment by cjubb39** [comment]
* Does 2 seconds per image seem enough? (currently at 1) Or even longer than that?
* That was my worry.  "click here" to link to the image instead? Since it looks like they will actually render even when not inlined.

**Comment by kaitlinhuben** [comment]
* 2 seconds is much better, 3 might be too long
* I like the "click here" idea, would like to add more in-depth description about what's actually being demonstrated. I can take a look at that when I'm done doing a few other things.

**Comment by cjubb39** [comment]
Alright.  I'm going to go ahead and merge this in, leaving #42 open for you or whoever to give more detail.

**Comment by kaitlinhuben** [comment]
Sounds good, thanks!

**Pull request merged**
