### PR TITLE
File I/O practice code

### PR DESCRIPTION
**Pull request by kl2532**
practice `fopen()` / `fclose()`, `fread()` / `fwrite()`, `fgets()` / `fputs()`

### CODE REVIEW

**Comment by danhcole** [comment]
Really nice coverage of the different uses of the various IO functions.  Can you also add a file with the expected output?

Two minor code issues: 
Line 42, there's an extra argument in ```fread()``` (doesn't compile)
A few of the fseek args are swapped (should be ```fseek(fp, 0, SEEK_SET)```, not ```fseek(fp, SEEK_SET, 0)```)

**Comment by kl2532** [comment]
fixed fseek() arguments + added output files
Is fread() causing a compilation error? It has 4 arguments (now line 53)

**Comment by danhcole** [comment]
Huh, strange...  LGTM now.

**Comment by ohEmily** [comment]
:+1:

**Pull request merged**
