### PR TITLE
C++: Remove "this" keyword Java comparison

### PR DESCRIPTION
**Pull request by kevin1**
In Java, the keyword `this` is also a reference to the current object. 

Source: [Oracle Java tutorial](https://docs.oracle.com/javase/tutorial/java/javaOO/thiskey.html)

### CODE REVIEW

**Comment by ohEmily** [comment]
I think that students appreciate references back to Java because it grounds them. I like your changes overall, but why remove the Java comparison?

**Comment by kevin1** [comment]
Here's the sentence I would like to remove:

> The C++ `this` is not to be confused with the Java `this`, **as the Java `this` is the object itself, rather than a pointer to it.**

It's kind of misleading because in Java, all objects are accessed with pointers -- they just use dot syntax `objref.member` instead of the C/C++ arrow `objref->member`. There is no concept of a Java object on the stack or passed by value.

It's a common misconception students have about Java. So the tradeoff I prefer is not reinforcing the misconception, even if it makes explaining the C++ syntax a little more difficult.

**Comment by jaewoolee** [comment]
Defnietly agree.  In fact, it should say the opposite:

"You probably guessed it.  The "this" keyword in C++ is the same thing as
the "this" keyword in Java.  What you know as object references in Java are
indeed none other than pointers.



- Jae

**Comment by ohEmily** [comment]
Yes that sounds much better.

I'm blown away that this was hiding in our recitation notes for all this
time, as I am about the bug Chaiwen found the other day. I'll put a note in
the next meeting agenda about this; maybe we should divvy up the notes and
have everyone do a clean up.

On Sat, Mar 5, 2016 at 12:35 PM, jaewoolee <notifications@github.com> wrote:

> Defnietly agree. In fact, it should say the opposite:
>
> "You probably guessed it. The "this" keyword in C++ is the same thing as
> the "this" keyword in Java. What you know as object references in Java are
> indeed none other than pointers.
>
>
>
> - Jae
>
>
> On Sat, Mar 5, 2016 at 12:31 PM, Kevin Chen <notifications@github.com>
> wrote:
>
> > Here's the sentence I would like to remove:
> >
> > The C++ this is not to be confused with the Java this, *as the Java this
> > is the object itself, rather than a pointer to it.*
> >
> > It's kind of misleading because in Java, all objects are accessed with
> > pointers -- they just use dot syntax objref.member instead of the C/C++
> > arrow objref->member. There is no concept of a Java object on the stack
> > or passed by value.
> >
> > It's a common misconception students have about Java. So the tradeoff I
> > prefer is not reinforcing the misconception, even if it makes explaining
> > the C++ syntax a little more difficult.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cs3157/recitations/pull/67#issuecomment-192695762>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cs3157/recitations/pull/67#issuecomment-192696947>.
>



-- 
emilypakulski.com

**Pull request merged**
