### PR TITLE
Changed clic-lab to clic

### PR DESCRIPTION
**Pull request by garymlin**
ssh your_uni@clic-lab.cs.columbia.edu --> ssh your_uni@clic.cs.columbia.edu

### CODE REVIEW

**Comment by leee** [comment]
Should most definitely mention how these two rotations differ.

Additionally, if someone is running persistent work that they'd like to get back to later, they should know their host's address. Being able to get a listing of current clic and clic-lab machines from DNS should help.

```
leee@marble-fox:~$ dig +short clic.cs.columbia.edu | xargs -L1 dig +short -x | sort
athens.clic.cs.columbia.edu.
beijing.clic.cs.columbia.edu.
brussels.clic.cs.columbia.edu.
delhi.clic.cs.columbia.edu.
paris.clic.cs.columbia.edu.
prague.clic.cs.columbia.edu.
sofia.clic.cs.columbia.edu.
tokyo.clic.cs.columbia.edu.
vienna.clic.cs.columbia.edu.
warsaw.clic.cs.columbia.edu.
leee@marble-fox:~$ dig +short clic-lab.clic.cs.columbia.edu | xargs -L1 dig +short -x | sort
algiers.clic.cs.columbia.edu.
amman.clic.cs.columbia.edu.
ankara.clic.cs.columbia.edu.
baghdad.clic.cs.columbia.edu.
beirut.clic.cs.columbia.edu.
bern.clic.cs.columbia.edu.
bucharest.clic.cs.columbia.edu.
budapest.clic.cs.columbia.edu.
cairo.clic.cs.columbia.edu.
damascus.clic.cs.columbia.edu.
dhaka.clic.cs.columbia.edu.
havana.clic.cs.columbia.edu.
islamabad.clic.cs.columbia.edu.
jerusalem.clic.cs.columbia.edu.
kathmandu.clic.cs.columbia.edu.
lisbon.clic.cs.columbia.edu.
moscow.clic.cs.columbia.edu.
nairobi.clic.cs.columbia.edu.
nassau.clic.cs.columbia.edu.
pretoria.clic.cs.columbia.edu.
rabat.clic.cs.columbia.edu.
santiago.clic.cs.columbia.edu.
suva.clic.cs.columbia.edu.
taipei.clic.cs.columbia.edu.
tripoli.clic.cs.columbia.edu.
wellington.clic.cs.columbia.edu.
yerevan.clic.cs.columbia.edu.
```

**Comment by DerekHXZ** [comment]
Note that clic-lab doesn't seem to be available outside Columbia network...


Sent from Outlook Mobile






On Sun, Feb 7, 2016 at 9:00 AM -0800, "Emily" <notifications@github.com> wrote:












Merged #60.

**Comment by ohEmily** [comment]
Yeah I think we should just only mention clic-lab in recitation, if at all. It's not a big loss.

**Comment by leee** [comment]
That's reasonable. @DerekHXZ, while you may not be able to dig the DNS rotation for clic-lab, it's hosts are still just as available as any other host on ColumbiaNet.

**Comment by kevin1** [comment]
Although clic-lab DNS is available outside of Columbia now, I think that was not the case a couple years ago

**Pull request merged**
